### ISSUE TITLE
Your domain is not working. Please check.

### ISSUE THREAD

**Issue by lzblack** [Mengyu-L/Project#1]

**Comment by Mengyu-L** [comment]
Dear Professor Li,

I am not sure what is happening that my domain is not working. The below
attachments are the screenshot of my domain and setting page.

Best,
Mengyu Liu

**Comment by lzblack** [comment]
I don't see the screenshots here. I guess GitHub does not support loading images from email directly.

**Comment by lzblack** [comment]
If you need help, we can schedule a quick Zoom meeting anytime today.

**Comment by Mengyu-L** [comment]
Dear Professor Li,

Thank you for your help, that will be great! I will be available all day.

Best,
Mengyu Liu

Zhi Li <notifications@github.com>于2021年2月25日 周四22:22写道：

**Comment by Mengyu-L** [comment]
Dear Professor Li,

The canvas doesn't allow me to re-submit the link. The link below is my
purchased domain.
www.myguzh-eng.site

Best,
Mengyu Liu

**Comment by Mengyu-L** [comment]
Hi Professor,

Could I have another quick zoom meeting with you? I have questions about
how to add my project to the visual studio.

Best,
Mengyu Liu

**Comment by lzblack** [comment]
Sorry I did not turn on GitHub notification. If you need to connect, please use Slack or email (directly to my email address). 

You can easily open the project in VS Code from GitHub Desktop.

**Comment by Mengyu-L** [comment]
I can’t find the project folder in GitHub Desktop. It suppose to be there,
but only project-proposal file is there.

Mengyu Liu

Zhi Li <notifications@github.com>于2021年2月26日 周五00:53写道：

**Comment by lzblack** [comment]
Then how did you create this repo?

**Comment by Mengyu-L** [comment]
我在网页上create的project folder，然后点开desktop他就不见了😭。

Zhi Li <notifications@github.com>于2021年2月26日 周五01:06写道：

**Comment by lzblack** [comment]
You need to clone the repo to your computer.

**Comment by Mengyu-L** [comment]
It says there are files in the project folder. Should I delete all of the
files and create a new one?

Zhi Li <notifications@github.com>于2021年2月26日 周五01:17写道：

**Comment by lzblack** [comment]
Who says?

**Comment by Mengyu-L** [comment]
The below attachment is the screenshot of the Github desktop.

**Comment by lzblack** [comment]
Again, I cannot see the attachment because email attachment is not supported by GitHub. You can paste it [here](https://github.com/Mengyu-L/Project/issues/1) in browser. Or Slack me.
