### ISSUE TITLE
Missing proposal

### ISSUE THREAD

**Issue by lzblack** [Mengyu-L/Project#2]

**Comment by Mengyu-L** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mengyu Liu's proposal</title>
    <style>
       body{background-color: antiquewhite;}
    </style>
</head>
<body>
   <b> 1. What is your project about?</b> 
   <p>I learned Guzheng for 15 years, I really want to share this traditional Chinese Instrument to the Western Country. I will include the history of Guzheng, different style of Guzheng, famous songs of Guzheng and my story with Guzheng. </p>   
    <b>2. What is the objective of your website? (Also read as why would this site be important?)</b>
    <p>My objective in the website is to introduce Guzheng this traditional chinese instrument and let more people in Western countries know about chinese instrument.</p>
    <b>3. Who is your target audience set?</b>
    <p>My target audience is whoever interested in learning different culture and love music </p>
    <b>4. What content do you plan to include in each page of your website?</b>
    <p>I will be including the history of Guzheng,different style of Guzheng, famous songs of Guzheng and my story with Guzheng. In these pages I will be using many images and some videos of Guzheng. </p>   
</body>
</html>

**Comment by Mengyu-L** [comment]
Already uploaded
